package sidecar

// Parameter represents a tool parameter from the manifest
type Parameter struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
}

// Manifest represents the tool manifest generated by the sidecar
type Manifest struct {
	ToolName    string      `json:"tool_name"`
	Description string      `json:"description"`
	Language    string      `json:"language"`
	Parameters  []Parameter `json:"parameters"`
	TestsPassed bool        `json:"tests_passed"`
}

// RunResult represents the result of a sidecar run
type RunResult struct {
	Manifest   *Manifest
	OutputPath string
	Success    bool
}